language: java
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy -DperformRelease=true -DskipTests=true
  --settings etc/settings.xml || mvn clean verify -DskipTests=true --settings etc/settings.xml'
env:
  global:
  - secure: F4NAUuiEONDdFMAGu6swOo3OmDiVhTrlyf9Ne/BYNs2Df5UhcAephaWsMB3DRoljKpZC6sWhpOjBaaFr4Za+/PerdOkxQUhq7S1V44+l9N47IAUDO94KTteLbmfieKqw4bpsy9LBLB6dN2uorch4zyk4d3tdcAxodEXXhSyXxeg=
  - secure: NR86hku3QneqhIpWsSMtVERHmyD9HNy6UJs9DboqOPQ/1BWe4L4KAUkzBzXquboAKoQt1fnkb8BBDhQsFOwzJGA0r1/xOuKNexF8Nz54dLl2flhguPzNxwPIy31brj4aN4nFPiSUZxidHBpvw8kVPE9wjoEyf+H3aFMR7LyJdoU=
